package Frames;

import entidades.Entrenador;
import entidades.Macrociclo;
import javax.swing.JOptionPane;

/**
 *
 * @author alanf
 */
public class cambiarParametros extends javax.swing.JFrame {

    /**
     * Creates new form CrearMCFrame
     * @param entrenador
     */
//    public CrearMCFrame(){
//        initComponents();
//        lblNombreEntrenador.setText("Prueba");
//        init();
//        setLocationRelativeTo(null);
//    }
    public cambiarParametros(Entrenador entrenador) {
        initComponents();
        lblNombreEntrenador.setText("Prueba");
        init();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        indicacionesLbl = new javax.swing.JLabel();
        deporteLbl = new javax.swing.JLabel();
        deporteCB = new javax.swing.JComboBox<>();
        ramaLbl = new javax.swing.JLabel();
        ramaCB = new javax.swing.JComboBox<>();
        jefeDeRamaLbl = new javax.swing.JLabel();
        jefeDeRamaCB = new javax.swing.JComboBox<>();
        entrenadorLbl = new javax.swing.JLabel();
        entrenadorCB = new javax.swing.JComboBox<>();
        metodologoLbl = new javax.swing.JLabel();
        metodologoCB = new javax.swing.JComboBox<>();
        siguienteBtn = new javax.swing.JButton();
        lblBienvenida = new javax.swing.JLabel();
        lblNombreEntrenador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear macrociclo");
        setResizable(false);

        indicacionesLbl.setText("Selecciona las opciones para editar el macrociclo.");

        deporteLbl.setText("Deporte");

        deporteCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Deporte 1", "Deporte 2", "Deporte 3", "Deporte 4" }));
        deporteCB.setToolTipText("");
        deporteCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                deporteCBItemStateChanged(evt);
            }
        });
        deporteCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deporteCBActionPerformed(evt);
            }
        });

        ramaLbl.setText("Rama");

        ramaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "rama 1", "rama 2", "rama 3", "rama 4" }));

        jefeDeRamaLbl.setText("Jefe de rama");

        jefeDeRamaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Jefe 1", "Jefe 2" }));

        entrenadorLbl.setText("Entrenador asignado");

        entrenadorCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "entrenador 1", "entrenador 2", "entrenador 3" }));

        metodologoLbl.setText("Metodólogo");

        metodologoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "metodólogo 1", "metodólogo 2", "metodólogo 3" }));

        siguienteBtn.setText("Siguiente");
        siguienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteBtnActionPerformed(evt);
            }
        });

        lblBienvenida.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblBienvenida.setText("Bienvenido entrenador");

        lblNombreEntrenador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombreEntrenador.setText("nombre entrenador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreEntrenador)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jefeDeRamaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jefeDeRamaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(metodologoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(metodologoCB, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entrenadorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entrenadorCB, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deporteLbl))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ramaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ramaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(deporteCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(indicacionesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(siguienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBienvenida)
                    .addComponent(lblNombreEntrenador))
                .addGap(3, 3, 3)
                .addComponent(indicacionesLbl)
                .addGap(18, 18, 18)
                .addComponent(deporteLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deporteCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(ramaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ramaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jefeDeRamaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jefeDeRamaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(metodologoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(metodologoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(entrenadorLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrenadorCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(siguienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteBtnActionPerformed
        // TODO add your handling code here:
       
        if ( validarCampos()) {
            String deporte= deporteCB.getSelectedItem().toString();
            String rama = ramaCB.getSelectedItem().toString();
            String jefeDeRama = jefeDeRamaCB.getSelectedItem().toString();
            String entrenador = entrenadorCB.getSelectedItem().toString();
            String metodologo = metodologoCB.getSelectedItem().toString();
            
            Macrociclo macrociclo = new Macrociclo(deporte, rama, jefeDeRama, entrenador, metodologo);

            new InicioFrame(macrociclo).setVisible(true);

        }else {
                JOptionPane.showMessageDialog(
                        null, // Componente padre (en este caso, ninguno)
                        "Ocurrió un error al ingresar los datos.",
                        "Error al ingresar los datos",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }
    }//GEN-LAST:event_siguienteBtnActionPerformed

    private void deporteCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deporteCBActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_deporteCBActionPerformed

    private void deporteCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_deporteCBItemStateChanged
        // TODO add your handling code here:
        String deporte = deporteCB.getSelectedItem().toString();
        ramaCB.setEnabled(true);
        switch (deporte) {
            case "Judo":
                ramaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Judo 1", "Judo 2", "Judo 3"}));
                break;
            case "Basquetbol":
                ramaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Basquetbol 1", "Basquetbol 2", "Basquetbol 3"}));
                break;

            case "Futbol":
                ramaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Futbol 1", "Futbol 2", "Futbol 3"}));
                break;
            case "Voleibol":
                ramaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Voleibol 1", "Voleibol 2", "Voleibol 3"}));
                break;
            case "Hockey":
                ramaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Hockey 1", "Hockey 2", "Hockey 3"}));
                break;

            case "Karate":
                ramaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Karate 1", "Karate 2", "Karate 3"}));
                break;
            case "Taekwondo":
                ramaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Takwondo 1", "Takwondo 2", "Takwondo 3"}));
                break;
            default:
            // Default secuencia de sentencias.
        }
    }//GEN-LAST:event_deporteCBItemStateChanged

    public void init() {
        ramaCB.setEnabled(false);
        jefeDeRamaCB.setEnabled(true);
        entrenadorCB.setEnabled(true);
        metodologoCB.setEnabled(true);
        deporteCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Judo", "Basquetbol", "Futbol", "Voleibol", "Hockey", "Karate", "Taekwondo"}));
    }

    public boolean validarCampos() {
        String deporteSeleccionado = deporteCB.getSelectedItem().toString();
        String ramaSeleccionada = ramaCB.getSelectedItem().toString();
        String jefeDeRamaSeleccionado = jefeDeRamaCB.getSelectedItem().toString();
        String entrenadorSeleccionado = entrenadorCB.getSelectedItem().toString();
        String metodologoSeleccionado = metodologoCB.getSelectedItem().toString();

        if ("Seleccionar".equals(deporteSeleccionado)
                || "Seleccionar".equals(ramaSeleccionada)
                || "Seleccionar".equals(jefeDeRamaSeleccionado)
                || "Seleccionar".equals(entrenadorSeleccionado)
                || "Seleccionar".equals(metodologoSeleccionado)) {
            // Mostrar mensaje de error
            JOptionPane.showMessageDialog(this, "Por favor, selecciona valores válidos en todos los campos",
                    "Error de Validación", JOptionPane.ERROR_MESSAGE);
        } else {
            return true;
            // Todos los campos son válidos, puedes continuar con tu lógica
            // ...
        }
        return false;
    }
/**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CrearMCFrame().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> deporteCB;
    private javax.swing.JLabel deporteLbl;
    private javax.swing.JComboBox<String> entrenadorCB;
    private javax.swing.JLabel entrenadorLbl;
    private javax.swing.JLabel indicacionesLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jefeDeRamaCB;
    private javax.swing.JLabel jefeDeRamaLbl;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblNombreEntrenador;
    private javax.swing.JComboBox<String> metodologoCB;
    private javax.swing.JLabel metodologoLbl;
    private javax.swing.JComboBox<String> ramaCB;
    private javax.swing.JLabel ramaLbl;
    private javax.swing.JButton siguienteBtn;
    // End of variables declaration//GEN-END:variables
}
