package Frames;

import autenticacion.IniciarSesionFrame;
import entidades.Entrenador;
import entidades.Macrociclo;
import javax.swing.JOptionPane;

/**
 *
 * @author alanf
 */
public class menuPrincipalFrame extends javax.swing.JFrame {

    Entrenador entrenador;
    

    /**
     * Creates new form CrearMCFrame
     *
     * @param entrenador
     * 
     */
//    public DatosMacrocicloFrame(){
//        initComponents();
//        lblNombreEntrenador.setText("Prueba");
//        init();
//        setLocationRelativeTo(null);
//    }
    public menuPrincipalFrame(Entrenador entrenador) {
        initComponents();
        lblNombreEntrenador.setText(entrenador.getNombre());
        
        this.entrenador = entrenador;
        btnEditarMacrociclo.setEnabled(false);
        btnEliminarMacrociclo.setEnabled(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnEliminarMacrociclo = new javax.swing.JButton();
        deporteLbl = new javax.swing.JLabel();
        comboMacrociclos = new javax.swing.JComboBox<>();
        indicacionesLbl = new javax.swing.JLabel();
        btnCrearMacrociclo = new javax.swing.JButton();
        btnEditarMacrociclo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        lblNombreEntrenador = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear macrociclo | Información Principal");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnEliminarMacrociclo.setBackground(new java.awt.Color(23, 110, 181));
        btnEliminarMacrociclo.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnEliminarMacrociclo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarMacrociclo.setText("Eliminar Macrociclo");
        btnEliminarMacrociclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMacrocicloActionPerformed(evt);
            }
        });

        deporteLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        deporteLbl.setForeground(new java.awt.Color(51, 51, 51));
        deporteLbl.setText("Macrociclos");

        comboMacrociclos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Macrociclo", "Macrociclo1", "Macrociclo2", "Macrociclo3", "Macrociclo4" }));

        indicacionesLbl.setBackground(new java.awt.Color(51, 51, 51));
        indicacionesLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        indicacionesLbl.setForeground(new java.awt.Color(51, 51, 51));
        indicacionesLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        indicacionesLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCrearMacrociclo.setBackground(new java.awt.Color(23, 110, 181));
        btnCrearMacrociclo.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnCrearMacrociclo.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearMacrociclo.setText("Crear Macrociclo");
        btnCrearMacrociclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMacrocicloActionPerformed(evt);
            }
        });

        btnEditarMacrociclo.setBackground(new java.awt.Color(23, 110, 181));
        btnEditarMacrociclo.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnEditarMacrociclo.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarMacrociclo.setText("Editar Macrociclo");
        btnEditarMacrociclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMacrocicloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(indicacionesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearMacrociclo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarMacrociclo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarMacrociclo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deporteLbl)
                    .addComponent(comboMacrociclos, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(indicacionesLbl)
                .addGap(46, 46, 46)
                .addComponent(deporteLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboMacrociclos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCrearMacrociclo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarMacrociclo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarMacrociclo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(23, 110, 181));

        lblBienvenida.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenida.setText("Bienvenido entrenador,");

        lblNombreEntrenador.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblNombreEntrenador.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreEntrenador.setText("Hugo Sanchez");

        btnCerrarSesion.setForeground(new java.awt.Color(51, 51, 51));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreEntrenador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBienvenida)
                    .addComponent(lblNombreEntrenador)
                    .addComponent(btnCerrarSesion))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        dispose();
        new IniciarSesionFrame().setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnEliminarMacrocicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMacrocicloActionPerformed

        

    }//GEN-LAST:event_btnEliminarMacrocicloActionPerformed

    private void btnCrearMacrocicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMacrocicloActionPerformed
        // TODO add your handling code here:
        if (validarCampos()){
            dispose();
            new SemanasFrame(entrenador).setVisible(true);
        }
    }//GEN-LAST:event_btnCrearMacrocicloActionPerformed

    private void btnEditarMacrocicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMacrocicloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarMacrocicloActionPerformed

    public boolean validarCampos() {
        String deporte = comboMacrociclos.getSelectedItem().toString();
        

        // Realiza las validaciones
        if(deporte.equals("Seleccione un deporte")){
            mostrarMensajeError("Por favor, selecciona un macrociclo.");
            return false;
        }
        
        if (esStringVacioONulo(deporte)) {
            mostrarMensajeError("Por favor, selecciona un macrociclo.");
            return false;
        }

        

        

        return true;
    }

    private boolean esStringVacioONulo(String str) {
        return str == null || str.trim().isEmpty();
    }

    private void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "Error de Entrada", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(semanasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(semanasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(semanasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(semanasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DatosMacrocicloFrame().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCrearMacrociclo;
    private javax.swing.JButton btnEditarMacrociclo;
    private javax.swing.JButton btnEliminarMacrociclo;
    private javax.swing.JComboBox<String> comboMacrociclos;
    private javax.swing.JLabel deporteLbl;
    private javax.swing.JLabel indicacionesLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblNombreEntrenador;
    // End of variables declaration//GEN-END:variables
}
