# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Show JDK location
      run: |
        ls -l /usr/lib/jvm
        echo "JAVA_HOME is: $JAVA_HOME"

    - name: tests presentacion
      run: ant -Dplatforms.JDK_17.home=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.2-7/x64 -f Macrociclo-Presentación/build.xml
